Topic1
julian-aiup/startup pull request #3
Opened 2016-10-12 13:22 UTC by julian-aiup

2016-10-12 16:12 UTC, cristian-cereseto requested changes
Just some comments, but overall looks good

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/index.html
> +  <body onload="fade();">
the ; is not needed here

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/index.html
> +        <br/>
the use of <br /> tags is not wrong, but you should try to use css to give layout to your code

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/index.html
> +    <script>window.jQuery || document.write('<script src="js/vendor/jquery-{{JQUERY_VERSION}}.min.js"><\/script>')</script>
mmmm this is not right, first..  i don't think you need jquery here and second i don't think this would work if you require it like this

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/js/index.js
> +    document.getElementById("fade-in").style.transition = "all 3s ease-out";
you can have the transition styles in a css class, and add and remove those classes instead of adding the style, that way you can reuse them

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/js/index.js
> +    var config = getConfig("GET", "https://api.github.com/search/repositories", true, { q: keyword });
As we discussed, instead of having a method _getConfig_, you can just declare a config object as

```
var config = {
   url: '...',
   method: '.....',
   async: true,
   .
   .
}
```

that way you can get rid of that function

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/js/index.js
> +        val = JSON.parse(val);
avoid using abbreviated variable names, use _value_ instead of _val_ to make the code more readable

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/js/index.js
> +          var node = document.createElement("li");
this variables (node and textNode) should be declared outside of the for and assigned here so that you are not declaring two variables in each cycle, also you should assign repositories-list in a variable, think that you are reaching for a DOM object every time the for runs and this impacts in the performance, you can refactor this to something like:

```
var node;
var repositoriesList = document.getElementById('repositories-list');
var textNode;

for (var key in val.items) {
   node = document.createElement('li');
   textNode = documente.createTextNode(val.items[key].full_name);

   repositoriesList.appendChild(node);
}
```

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/js/index.js
> +    var uri = getURI(config["url"], config["params"]);
you can access object properties as config.url

2016-10-12 16:12 UTC, cristian-cereseto commented on 01-JS-DOM-APIs/table.html
> +    <script>window.jQuery || document.write('<script src="js/vendor/jquery-{{JQUERY_VERSION}}.min.js"><\/script>')</script>
Same as above, don't think you're using jquery, right?

2016-10-13 12:22 UTC, julian-aiup commented on 01-JS-DOM-APIs/index.html
> +    <script>window.jQuery || document.write('<script src="js/vendor/jquery-{{JQUERY_VERSION}}.min.js"><\/script>')</script>
oh, I used a [HTML5 boilerplate I found on topic0](https://raw.githubusercontent.com/h5bp/html5-boilerplate/master/src/index.html)... I'll just delete that then

2016-10-13 14:12 UTC, afiorenza requested changes
Good job! just a few changes

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +        <label for="keyword-repositories">Search repositories: </label>
The label should wrap the input. This should be:

```
<label for="keyword-repositories"> 
  Search repositories: <input type="text" name="keyword-repositories" id="keyword-repositories">
</label>
```

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/index.js
> +        var node;
We should use let and const instead var

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/index.js
> +        document.getElementById("fade-in").style.color = "red";
You are using this `document.getElementById("fade-in")` twice. You should store this into a variable.

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/table.js
> +let arr = [];
This variable name could be more descriptive :/

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/table.js
> +  for (var r = 0; r < arr.length; r++) {
It is better to use map to map an array. Here you could find documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/table.js
> +    var rowNode = document.createElement("tr");
It is better to declare variables outside the for loops in order to avoid declarate this in every loop

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/css/style.css
> +  position: absolute;
Remember to alphaorder css rules

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +        <section class="hidden" id="fade-in">
Why you use `class` and `id`?

2016-10-13 14:12 UTC, afiorenza commented on 01-JS-DOM-APIs/js/index.js
> +    }
`;` after the `{`

2016-10-17 12:12 UTC, julian-aiup commented on 01-JS-DOM-APIs/index.html
> +        <label for="keyword-repositories">Search repositories: </label>
ok

2016-10-17 12:16 UTC, julian-aiup commented on 01-JS-DOM-APIs/index.html
> +        <section class="hidden" id="fade-in">
because I add style to the class with css and I need to identify the element with JS

2016-10-17 12:17 UTC, julian-aiup commented on 01-JS-DOM-APIs/js/index.js
> +    }
ok

2016-10-17 12:22 UTC, julian-aiup commented on 01-JS-DOM-APIs/js/index.js
> +        var node;
ok

2016-10-17 12:27 UTC, julian-aiup commented on 01-JS-DOM-APIs/js/index.js
> +        document.getElementById("fade-in").style.color = "red";
ok

2016-10-17 12:49 UTC, jaiup commented on 01-JS-DOM-APIs/js/table.js
> +  for (var r = 0; r < arr.length; r++) {
ok

2016-10-17 12:50 UTC, julian-aiup commented on 01-JS-DOM-APIs/js/table.js
> +    var rowNode = document.createElement("tr");
ok

2016-10-17 12:51 UTC, julian-aiup commented on 01-JS-DOM-APIs/js/table.js
> +let arr = [];
ok

2016-10-17 12:57 UTC, julian-aiup commented on 01-JS-DOM-APIs/css/style.css
> +  position: absolute;
css rules are grouped by categories (box properties, box borders, ...) and then alphaordered

> **Order properties: box, border, background, text & other**
Always order your properties grouping by categories. Box properties (Position, layout, display), box borders, background properties, text properties (font size, family, weight, etc), and so on.

2016-10-17 14:08 UTC, afiorenza commented on 01-JS-DOM-APIs/css/style.css
> +  position: absolute;
Okey! fair enough

2016-10-17 14:09 UTC, afiorenza approved these changes
Ready for merge!

2016-10-17 15:55 UTC, merged