Julian Aiup Topic2 - Exercise 1.Create Movie class
julian-aiup/startup pull request #4
Opened 2016-10-13 14:50 UTC by julian-aiup

2016-10-18 15:25 UTC, afiorenza requested changes
Perfect work! just a few changes!

2016-10-18 15:25 UTC, afiorenza commented on 02-oop-inheritance/js/index.js
> +      if (event === element.name) return element;
This is okey, but for reading and maintainability purpose the if block should be 

```
if (condition) {
  statements
}
```  

event if the statement is one line

2016-10-18 15:25 UTC, afiorenza commented on 02-oop-inheritance/js/index.js
> +    console.log("The '" + info + "' event has been emmited");
Can you pass the movie and log the title? Also use template string. Thanks!

2016-10-19 12:19 UTC, julian-aiup commented on 02-oop-inheritance/js/index.js
> +      if (event === element.name) return element;
ok

2016-10-19 12:19 UTC, julian-aiup commented on 02-oop-inheritance/js/index.js
> +    console.log("The '" + info + "' event has been emmited");
ok

2016-10-19 16:58 UTC, afiorenza approved these changes
Good job! Ready for merge.Congrats!

2016-10-20 11:58 UTC, merged