Topic4
julian-aiup/startup pull request #5
Opened 2016-10-20 15:55 UTC by julian-aiup

2016-10-24 12:09 UTC, afiorenza reviewed
Everything okey. But i see that you are using strings like "comment" and "commentIndex" several times. Could you move them to constants in order to make this more maintainable? Thanks!

2016-10-24 14:06 UTC, afiorenza requested changes
Well done! just a few changes

2016-10-24 14:06 UTC, afiorenza commented on 04-HTML5-APIs/js/web-socket.js
> +  pre.style.wordWrap = "break-word";
It is better to have the style in a css stylesheet.

2016-10-24 14:06 UTC, afiorenza commented on 04-HTML5-APIs/js/web-socket.js
> +  let pre = document.createElement("p");
I think `pre` is not a descriptive name. Could you find a better name?

2016-10-24 14:06 UTC, afiorenza commented on 04-HTML5-APIs/js/web-socket.js
> +  writeToScreen('<span style="color: blue;">RESPONSE: ' + evt.data + '</span>');
Style should go in the css and you should set a class to this span.

2016-10-24 14:06 UTC, afiorenza commented on 04-HTML5-APIs/js/drag-and-drop.js
> +  document.getElementById("drop").textContent = '';
You already declare drop (`document.getElementById("drop")`) above. You can reuse it.

2016-10-24 15:54 UTC, julian-aiup commented on 04-HTML5-APIs/js/web-socket.js
> +  writeToScreen('<span style="color: blue;">RESPONSE: ' + evt.data + '</span>');
ok

2016-10-24 15:54 UTC, julian-aiup commented on 04-HTML5-APIs/js/web-socket.js
> +  let pre = document.createElement("p");
ok

2016-10-24 15:54 UTC, julian-aiup commented on 04-HTML5-APIs/js/web-socket.js
> +  pre.style.wordWrap = "break-word";
ok

2016-10-24 15:55 UTC, julian-aiup commented on 04-HTML5-APIs/js/drag-and-drop.js
> +  document.getElementById("drop").textContent = '';
ok

2016-11-01 17:17 UTC, afiorenza approved these changes

2016-11-02 11:54 UTC, merged